/*
 * Copyright 2024 NXP
 *
 * SPDX-License-Identifier: BSD-3-Clause
 */

/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

/* clang-format off */
/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
!!GlobalInfo
product: Pins v13.0
processor: MCXW716CxxxA
package_id: MCXW716CMFTA
mcu_data: ksdk2_0
processor_version: 0.15.4
pin_labels:
- {pin_num: '2', pin_signal: PTB4/WUU0_P15/LPSPI1_PCS3/LPUART1_CTS_b/LPI2C1_SDA/I3C0_SDA/TRGMUX0_IN0/FLEXIO0_D30, label: LPI2C1_SDA, identifier: LPSPI1_PCS3;LPI2C1_SDA}
- {pin_num: '3', pin_signal: PTB5/LPSPI1_PCS2/LPUART1_RTS_b/LPI2C1_SCL/I3C0_SCL/TRGMUX0_OUT0/FLEXIO0_D31, label: LPI2C1_SCL, identifier: LPI2C1_SCL}
- {pin_num: '48', pin_signal: ADC0_B12/PTB2/LPSPI1_SCK/LPUART1_TX/TPM1_CH2/FLEXIO0_D28, label: LPSPI1_SCK, identifier: LPSPI1_SCK}
- {pin_num: '47', pin_signal: ADC0_B11/PTB1/LPSPI1_SIN/TPM1_CH1/FLEXIO0_D27, label: LPSPI1_IN, identifier: LPSPI1_IN}
- {pin_num: '1', pin_signal: ADC0_B13/PTB3/WUU0_P14/LPSPI1_SOUT/LPUART1_RX/TPM1_CH3/FLEXIO0_D29, label: LPSPI1_OUT, identifier: LPSPI1_OUT}
- {pin_num: '46', pin_signal: ADC0_B10/PTB0/WUU0_P13/LPSPI1_PCS0/TPM1_CH0/FLEXIO0_D26, label: LPSPI1_PCS0, identifier: LPSPI1_PCS0}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */
/* clang-format on */

#include "fsl_common.h"
#include "fsl_port.h"
#include "fsl_gpio.h"
#include "pin_mux.h"

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitBootPins
 * Description   : Calls initialization functions.
 *
 * END ****************************************************************************************************************/
void BOARD_InitBootPins(void)
{
    BOARD_InitPins();
}

/* clang-format off */
/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
BOARD_InitPins:
- options: {callFromInitBoot: 'true', coreID: cm33, enableClock: 'true'}
- pin_list:
  - {pin_num: '39', peripheral: LPUART1, signal: RX, pin_signal: PTC2/WUU0_P9/LPSPI1_SOUT/LPUART1_RX/LPI2C1_SCLS/TPM1_CH2/I3C0_PUR/FLEXIO0_D18, pull_select: down,
    pull_enable: disable, slew_rate: fast, open_drain: disable, drive_strength: low}
  - {pin_num: '40', peripheral: LPUART1, signal: TX, pin_signal: PTC3/LPSPI1_SCK/LPUART1_TX/LPI2C1_SDAS/TPM1_CH3/FLEXIO0_D19, pull_select: down, pull_enable: disable,
    slew_rate: fast, open_drain: disable, drive_strength: low}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */
/* clang-format on */

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitPins
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
void BOARD_InitPins(void)
{
    /* Clock Configuration: Peripheral clocks are enabled; module does not stall low power mode entry */
    CLOCK_EnableClock(kCLOCK_GpioA);
    /* Clock Configuration: Peripheral clocks are enabled; module does not stall low power mode entry */
    CLOCK_EnableClock(kCLOCK_PortA);
    /* Clock Configuration: Peripheral clocks are enabled; module does not stall low power mode entry */
    CLOCK_EnableClock(kCLOCK_PortC);


    const port_pin_config_t portc2_pin39_config = {/* Internal pull-up/down resistor is disabled */
                                                   (uint16_t)kPORT_PullDisable,
                                                   /* Low internal pull resistor value is selected. */
                                                   (uint16_t)kPORT_LowPullResistor,
                                                   /* Fast slew rate is configured */
                                                   (uint16_t)kPORT_FastSlewRate,
                                                   /* Passive input filter is disabled */
                                                   (uint16_t)kPORT_PassiveFilterDisable,
                                                   /* Open drain output is disabled */
                                                   (uint16_t)kPORT_OpenDrainDisable,
                                                   /* Low drive strength is configured */
                                                   (uint16_t)kPORT_LowDriveStrength,
                                                   /* Normal drive strength is configured */
                                                   (uint16_t)kPORT_NormalDriveStrength,
                                                   /* Pin is configured as LPUART1_RX */
                                                   (uint16_t)kPORT_MuxAlt3,
                                                   /* Pin Control Register fields [15:0] are not locked */
                                                   (uint16_t)kPORT_UnlockRegister};
    /* PORTC2 (pin 39) is configured as LPUART1_RX */
    PORT_SetPinConfig(PORTC, 2U, &portc2_pin39_config);

    const port_pin_config_t portc3_pin40_config = {/* Internal pull-up/down resistor is disabled */
                                                   (uint16_t)kPORT_PullDisable,
                                                   /* Low internal pull resistor value is selected. */
                                                   (uint16_t)kPORT_LowPullResistor,
                                                   /* Fast slew rate is configured */
                                                   (uint16_t)kPORT_FastSlewRate,
                                                   /* Passive input filter is disabled */
                                                   (uint16_t)kPORT_PassiveFilterDisable,
                                                   /* Open drain output is disabled */
                                                   (uint16_t)kPORT_OpenDrainDisable,
                                                   /* Low drive strength is configured */
                                                   (uint16_t)kPORT_LowDriveStrength,
                                                   /* Normal drive strength is configured */
                                                   (uint16_t)kPORT_NormalDriveStrength,
                                                   /* Pin is configured as LPUART1_TX */
                                                   (uint16_t)kPORT_MuxAlt3,
                                                   /* Pin Control Register fields [15:0] are not locked */
                                                   (uint16_t)kPORT_UnlockRegister};
    /* PORTC3 (pin 40) is configured as LPUART1_TX */
    PORT_SetPinConfig(PORTC, 3U, &portc3_pin40_config);

    gpio_pin_config_t LED_GREEN_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PTA19 (pin 14)  */
    GPIO_PinInit(BOARD_INITPINS_LED_GREEN_GPIO, BOARD_INITPINS_LED_GREEN_PIN, &LED_GREEN_config);

    const port_pin_config_t LED_GREEN = {/* Internal pull-up/down resistor is disabled */
                                         (uint16_t)kPORT_PullDisable,
                                         /* Low internal pull resistor value is selected. */
                                         (uint16_t)kPORT_LowPullResistor,
                                         /* Fast slew rate is configured */
                                         (uint16_t)kPORT_FastSlewRate,
                                         /* Passive input filter is disabled */
                                         (uint16_t)kPORT_PassiveFilterDisable,
                                         /* Open drain output is disabled */
                                         (uint16_t)kPORT_OpenDrainDisable,
                                         /* Low drive strength is configured */
                                         (uint16_t)kPORT_LowDriveStrength,
                                         /* Normal drive strength is configured */
                                         (uint16_t)kPORT_NormalDriveStrength,
                                         /* Pin is configured as PTA19 */
                                         (uint16_t)kPORT_MuxAsGpio,
                                         /* Pin Control Register fields [15:0] are not locked */
                                         (uint16_t)kPORT_UnlockRegister};
    /* PORTA19 (pin 14) is configured as PTA19 */
    PORT_SetPinConfig(BOARD_INITPINS_LED_GREEN_PORT, BOARD_INITPINS_LED_GREEN_PIN, &LED_GREEN);

    /* Initialize GPIO functionality on pin PTA19 (pin 14)  */
    GPIO_PinInit(BOARD_INITPINS_LED_BLUE_GPIO, BOARD_INITPINS_LED_BLUE_PIN, &LED_GREEN_config);

    const port_pin_config_t LED_BLUE = {/* Internal pull-up/down resistor is disabled */
                                         (uint16_t)kPORT_PullDisable,
                                         /* Low internal pull resistor value is selected. */
                                         (uint16_t)kPORT_LowPullResistor,
                                         /* Fast slew rate is configured */
                                         (uint16_t)kPORT_FastSlewRate,
                                         /* Passive input filter is disabled */
                                         (uint16_t)kPORT_PassiveFilterDisable,
                                         /* Open drain output is disabled */
                                         (uint16_t)kPORT_OpenDrainDisable,
                                         /* Low drive strength is configured */
                                         (uint16_t)kPORT_LowDriveStrength,
                                         /* Normal drive strength is configured */
                                         (uint16_t)kPORT_NormalDriveStrength,
                                         /* Pin is configured as PTA19 */
                                         (uint16_t)kPORT_MuxAsGpio,
                                         /* Pin Control Register fields [15:0] are not locked */
                                         (uint16_t)kPORT_UnlockRegister};
    /* PORTA19 (pin 14) is configured as PTA19 */
    PORT_SetPinConfig(BOARD_INITPINS_LED_BLUE_PORT, BOARD_INITPINS_LED_BLUE_PIN, &LED_BLUE);

    /* Initialize GPIO functionality on pin PTA19 (pin 14)  */
    GPIO_PinInit(BOARD_INITPINS_LED_RED_GPIO, BOARD_INITPINS_LED_RED_PIN, &LED_GREEN_config);

    const port_pin_config_t LED_RED = {/* Internal pull-up/down resistor is disabled */
                                         (uint16_t)kPORT_PullDisable,
                                         /* Low internal pull resistor value is selected. */
                                         (uint16_t)kPORT_LowPullResistor,
                                         /* Fast slew rate is configured */
                                         (uint16_t)kPORT_FastSlewRate,
                                         /* Passive input filter is disabled */
                                         (uint16_t)kPORT_PassiveFilterDisable,
                                         /* Open drain output is disabled */
                                         (uint16_t)kPORT_OpenDrainDisable,
                                         /* Low drive strength is configured */
                                         (uint16_t)kPORT_LowDriveStrength,
                                         /* Normal drive strength is configured */
                                         (uint16_t)kPORT_NormalDriveStrength,
                                         /* Pin is configured as PTA19 */
                                         (uint16_t)kPORT_MuxAsGpio,
                                         /* Pin Control Register fields [15:0] are not locked */
                                         (uint16_t)kPORT_UnlockRegister};
    /* PORTA19 (pin 14) is configured as PTA19 */
    PORT_SetPinConfig(BOARD_INITPINS_LED_RED_PORT, BOARD_INITPINS_LED_RED_PIN, &LED_RED);
}

/* clang-format off */
/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
LPI2C1_InitPins:
- options: {callFromInitBoot: 'false', coreID: cm33, enableClock: 'true'}
- pin_list:
  - {pin_num: '3', peripheral: LPI2C1, signal: SCL, pin_signal: PTB5/LPSPI1_PCS2/LPUART1_RTS_b/LPI2C1_SCL/I3C0_SCL/TRGMUX0_OUT0/FLEXIO0_D31, pull_select: up, pull_enable: enable,
    slew_rate: fast, passive_filter: disable, open_drain: disable, drive_strength: low, drive_strength_1: normal}
  - {pin_num: '2', peripheral: LPI2C1, signal: SDA, pin_signal: PTB4/WUU0_P15/LPSPI1_PCS3/LPUART1_CTS_b/LPI2C1_SDA/I3C0_SDA/TRGMUX0_IN0/FLEXIO0_D30, identifier: LPI2C1_SDA,
    pull_select: up, pull_enable: enable, pull_value: low, slew_rate: fast, passive_filter: disable, open_drain: disable, drive_strength: low, drive_strength_1: normal}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */
/* clang-format on */

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : LPI2C1_InitPins
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
void LPI2C1_InitPins(void)
{
    /* Clock Configuration: Peripheral clocks are enabled; module does not stall low power mode entry */
    CLOCK_EnableClock(kCLOCK_PortB);

    const port_pin_config_t LPI2C1_SDA = {/* Internal pull-up resistor is enabled */
                                          (uint16_t)kPORT_PullUp,
                                          /* Low internal pull resistor value is selected. */
                                          (uint16_t)kPORT_LowPullResistor,
                                          /* Fast slew rate is configured */
                                          (uint16_t)kPORT_FastSlewRate,
                                          /* Passive input filter is disabled */
                                          (uint16_t)kPORT_PassiveFilterDisable,
                                          /* Open drain output is disabled */
                                          (uint16_t)kPORT_OpenDrainDisable,
                                          /* Low drive strength is configured */
                                          (uint16_t)kPORT_LowDriveStrength,
                                          /* Normal drive strength is configured */
                                          (uint16_t)kPORT_NormalDriveStrength,
                                          /* Pin is configured as LPI2C1_SDA */
                                          (uint16_t)kPORT_MuxAlt4,
                                          /* Pin Control Register fields [15:0] are not locked */
                                          (uint16_t)kPORT_UnlockRegister};
    /* PORTB4 (pin 2) is configured as LPI2C1_SDA */
    PORT_SetPinConfig(LPI2C1_INITPINS_LPI2C1_SDA_PORT, LPI2C1_INITPINS_LPI2C1_SDA_PIN, &LPI2C1_SDA);

    const port_pin_config_t LPI2C1_SCL = {/* Internal pull-up resistor is enabled */
                                          (uint16_t)kPORT_PullUp,
                                          /* Low internal pull resistor value is selected. */
                                          (uint16_t)kPORT_LowPullResistor,
                                          /* Fast slew rate is configured */
                                          (uint16_t)kPORT_FastSlewRate,
                                          /* Passive input filter is disabled */
                                          (uint16_t)kPORT_PassiveFilterDisable,
                                          /* Open drain output is disabled */
                                          (uint16_t)kPORT_OpenDrainDisable,
                                          /* Low drive strength is configured */
                                          (uint16_t)kPORT_LowDriveStrength,
                                          /* Normal drive strength is configured */
                                          (uint16_t)kPORT_NormalDriveStrength,
                                          /* Pin is configured as LPI2C1_SCL */
                                          (uint16_t)kPORT_MuxAlt4,
                                          /* Pin Control Register fields [15:0] are not locked */
                                          (uint16_t)kPORT_UnlockRegister};
    /* PORTB5 (pin 3) is configured as LPI2C1_SCL */
    PORT_SetPinConfig(LPI2C1_INITPINS_LPI2C1_SCL_PORT, LPI2C1_INITPINS_LPI2C1_SCL_PIN, &LPI2C1_SCL);
}

/* clang-format off */
/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
LPI2C1_DeinitPins:
- options: {callFromInitBoot: 'false', coreID: cm33, enableClock: 'true'}
- pin_list:
  - {pin_num: '2', peripheral: n/a, signal: disabled, pin_signal: PTB4/WUU0_P15/LPSPI1_PCS3/LPUART1_CTS_b/LPI2C1_SDA/I3C0_SDA/TRGMUX0_IN0/FLEXIO0_D30, pull_select: down,
    pull_enable: disable, pull_value: low, slew_rate: fast, passive_filter: disable, open_drain: disable, drive_strength: low, drive_strength_1: normal}
  - {pin_num: '3', peripheral: n/a, signal: disabled, pin_signal: PTB5/LPSPI1_PCS2/LPUART1_RTS_b/LPI2C1_SCL/I3C0_SCL/TRGMUX0_OUT0/FLEXIO0_D31, pull_select: down,
    pull_enable: disable, slew_rate: fast, passive_filter: disable, open_drain: disable, drive_strength: low, drive_strength_1: normal}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */
/* clang-format on */

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : LPI2C1_DeinitPins
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
void LPI2C1_DeinitPins(void)
{
    /* Clock Configuration: Peripheral clocks are enabled; module does not stall low power mode entry */
    CLOCK_EnableClock(kCLOCK_PortB);

    const port_pin_config_t portb4_pin2_config = {/* Internal pull-up/down resistor is disabled */
                                                  (uint16_t)kPORT_PullDisable,
                                                  /* Low internal pull resistor value is selected. */
                                                  (uint16_t)kPORT_LowPullResistor,
                                                  /* Fast slew rate is configured */
                                                  (uint16_t)kPORT_FastSlewRate,
                                                  /* Passive input filter is disabled */
                                                  (uint16_t)kPORT_PassiveFilterDisable,
                                                  /* Open drain output is disabled */
                                                  (uint16_t)kPORT_OpenDrainDisable,
                                                  /* Low drive strength is configured */
                                                  (uint16_t)kPORT_LowDriveStrength,
                                                  /* Normal drive strength is configured */
                                                  (uint16_t)kPORT_NormalDriveStrength,
                                                  /* Pin is disabled */
                                                  (uint16_t)kPORT_PinDisabledOrAnalog,
                                                  /* Pin Control Register fields [15:0] are not locked */
                                                  (uint16_t)kPORT_UnlockRegister};
    /* PORTB4 (pin 2) is disabled */
    PORT_SetPinConfig(PORTB, 4U, &portb4_pin2_config);

    const port_pin_config_t LPI2C1_SCL = {/* Internal pull-up/down resistor is disabled */
                                          (uint16_t)kPORT_PullDisable,
                                          /* Low internal pull resistor value is selected. */
                                          (uint16_t)kPORT_LowPullResistor,
                                          /* Fast slew rate is configured */
                                          (uint16_t)kPORT_FastSlewRate,
                                          /* Passive input filter is disabled */
                                          (uint16_t)kPORT_PassiveFilterDisable,
                                          /* Open drain output is disabled */
                                          (uint16_t)kPORT_OpenDrainDisable,
                                          /* Low drive strength is configured */
                                          (uint16_t)kPORT_LowDriveStrength,
                                          /* Normal drive strength is configured */
                                          (uint16_t)kPORT_NormalDriveStrength,
                                          /* Pin is disabled */
                                          (uint16_t)kPORT_PinDisabledOrAnalog,
                                          /* Pin Control Register fields [15:0] are not locked */
                                          (uint16_t)kPORT_UnlockRegister};
    /* PORTB5 (pin 3) is disabled */
    PORT_SetPinConfig(LPI2C1_DEINITPINS_LPI2C1_SCL_PORT, LPI2C1_DEINITPINS_LPI2C1_SCL_PIN, &LPI2C1_SCL);
}

/* clang-format off */
/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
LPSPI0_InitPins:
- options: {callFromInitBoot: 'false', coreID: cm33, enableClock: 'true'}
- pin_list:
  - {pin_num: '11', peripheral: LPSPI0, signal: PCS0, pin_signal: ADC0_A12/PTA16/RF_NOT_ALLOWED/LPSPI0_PCS0/EWM0_OUT_b/LPI2C0_SCLS/TPM0_CH4/LPUART0_RX/RF_GPO_8/FLEXIO0_D5,
    pull_select: up, pull_enable: enable, slew_rate: fast, open_drain: disable, drive_strength: low}
  - {pin_num: '14', peripheral: LPSPI0, signal: SCK, pin_signal: CMP1_IN0/PTA19/WUU0_P4/LPSPI0_SCK/LPUART0_RTS_b/LPI2C0_SCL/TPM0_CH2/RF_GPO_1, pull_select: up, pull_enable: enable,
    pull_value: low, slew_rate: fast, passive_filter: disable, open_drain: disable, drive_strength: low, drive_strength_1: normal}
  - {pin_num: '12', peripheral: LPSPI0, signal: IN, pin_signal: ADC0_A13/PTA17/WUU0_P3/RF_NOT_ALLOWED/LPSPI0_SIN/EWM0_IN/LPI2C0_SDAS/TPM0_CH5/LPUART0_TX/RF_GPO_7/RF_GPO_8/FLEXIO0_D6,
    pull_select: up, pull_enable: enable, slew_rate: fast, open_drain: disable, drive_strength: low}
  - {pin_num: '13', peripheral: LPSPI0, signal: OUT, pin_signal: CMP1_IN1/PTA18/LPSPI0_SOUT/LPUART0_CTS_b/LPI2C0_SDA/TPM0_CH3/RF_GPO_0/LPUART0_RX, pull_select: up,
    pull_enable: enable, pull_value: low, slew_rate: fast, passive_filter: disable, open_drain: disable, drive_strength: low, drive_strength_1: normal}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */
/* clang-format on */

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : LPSPI0_InitPins
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
void LPSPI0_InitPins(void)
{
    /* Clock Configuration: Peripheral clocks are enabled; module does not stall low power mode entry */
    CLOCK_EnableClock(kCLOCK_PortA);

    const port_pin_config_t porta16_pin11_config = {/* Internal pull-up resistor is enabled */
                                                    (uint16_t)kPORT_PullUp,
                                                    /* Low internal pull resistor value is selected. */
                                                    (uint16_t)kPORT_LowPullResistor,
                                                    /* Fast slew rate is configured */
                                                    (uint16_t)kPORT_FastSlewRate,
                                                    /* Passive input filter is disabled */
                                                    (uint16_t)kPORT_PassiveFilterDisable,
                                                    /* Open drain output is disabled */
                                                    (uint16_t)kPORT_OpenDrainDisable,
                                                    /* Low drive strength is configured */
                                                    (uint16_t)kPORT_LowDriveStrength,
                                                    /* Normal drive strength is configured */
                                                    (uint16_t)kPORT_NormalDriveStrength,
                                                    /* Pin is configured as LPSPI0_PCS0 */
                                                    (uint16_t)kPORT_MuxAlt2,
                                                    /* Pin Control Register fields [15:0] are not locked */
                                                    (uint16_t)kPORT_UnlockRegister};
    /* PORTA16 (pin 11) is configured as LPSPI0_PCS0 */
    PORT_SetPinConfig(PORTA, 16U, &porta16_pin11_config);

    const port_pin_config_t porta17_pin12_config = {/* Internal pull-up resistor is enabled */
                                                    (uint16_t)kPORT_PullUp,
                                                    /* Low internal pull resistor value is selected. */
                                                    (uint16_t)kPORT_LowPullResistor,
                                                    /* Fast slew rate is configured */
                                                    (uint16_t)kPORT_FastSlewRate,
                                                    /* Passive input filter is disabled */
                                                    (uint16_t)kPORT_PassiveFilterDisable,
                                                    /* Open drain output is disabled */
                                                    (uint16_t)kPORT_OpenDrainDisable,
                                                    /* Low drive strength is configured */
                                                    (uint16_t)kPORT_LowDriveStrength,
                                                    /* Normal drive strength is configured */
                                                    (uint16_t)kPORT_NormalDriveStrength,
                                                    /* Pin is configured as LPSPI0_SIN */
                                                    (uint16_t)kPORT_MuxAlt2,
                                                    /* Pin Control Register fields [15:0] are not locked */
                                                    (uint16_t)kPORT_UnlockRegister};
    /* PORTA17 (pin 12) is configured as LPSPI0_SIN */
    PORT_SetPinConfig(PORTA, 17U, &porta17_pin12_config);

    const port_pin_config_t porta18_pin13_config = {/* Internal pull-up resistor is enabled */
                                                    (uint16_t)kPORT_PullUp,
                                                    /* Low internal pull resistor value is selected. */
                                                    (uint16_t)kPORT_LowPullResistor,
                                                    /* Fast slew rate is configured */
                                                    (uint16_t)kPORT_FastSlewRate,
                                                    /* Passive input filter is disabled */
                                                    (uint16_t)kPORT_PassiveFilterDisable,
                                                    /* Open drain output is disabled */
                                                    (uint16_t)kPORT_OpenDrainDisable,
                                                    /* Low drive strength is configured */
                                                    (uint16_t)kPORT_LowDriveStrength,
                                                    /* Normal drive strength is configured */
                                                    (uint16_t)kPORT_NormalDriveStrength,
                                                    /* Pin is configured as LPSPI0_SOUT */
                                                    (uint16_t)kPORT_MuxAlt2,
                                                    /* Pin Control Register fields [15:0] are not locked */
                                                    (uint16_t)kPORT_UnlockRegister};
    /* PORTA18 (pin 13) is configured as LPSPI0_SOUT */
    PORT_SetPinConfig(PORTA, 18U, &porta18_pin13_config);

    const port_pin_config_t porta19_pin14_config = {/* Internal pull-up resistor is enabled */
                                                    (uint16_t)kPORT_PullUp,
                                                    /* Low internal pull resistor value is selected. */
                                                    (uint16_t)kPORT_LowPullResistor,
                                                    /* Fast slew rate is configured */
                                                    (uint16_t)kPORT_FastSlewRate,
                                                    /* Passive input filter is disabled */
                                                    (uint16_t)kPORT_PassiveFilterDisable,
                                                    /* Open drain output is disabled */
                                                    (uint16_t)kPORT_OpenDrainDisable,
                                                    /* Low drive strength is configured */
                                                    (uint16_t)kPORT_LowDriveStrength,
                                                    /* Normal drive strength is configured */
                                                    (uint16_t)kPORT_NormalDriveStrength,
                                                    /* Pin is configured as LPSPI0_SCK */
                                                    (uint16_t)kPORT_MuxAlt2,
                                                    /* Pin Control Register fields [15:0] are not locked */
                                                    (uint16_t)kPORT_UnlockRegister};
    /* PORTA19 (pin 14) is configured as LPSPI0_SCK */
    PORT_SetPinConfig(PORTA, 19U, &porta19_pin14_config);
}

/* clang-format off */
/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
LPSPI1_InitPins:
- options: {callFromInitBoot: 'false', coreID: cm33, enableClock: 'true'}
- pin_list:
  - {pin_num: '48', peripheral: LPSPI1, signal: SCK, pin_signal: ADC0_B12/PTB2/LPSPI1_SCK/LPUART1_TX/TPM1_CH2/FLEXIO0_D28, pull_select: up, pull_enable: enable, slew_rate: fast,
    open_drain: disable, drive_strength: high}
  - {pin_num: '47', peripheral: LPSPI1, signal: IN, pin_signal: ADC0_B11/PTB1/LPSPI1_SIN/TPM1_CH1/FLEXIO0_D27, pull_select: up, pull_enable: enable, slew_rate: fast,
    open_drain: disable, drive_strength: high}
  - {pin_num: '1', peripheral: LPSPI1, signal: OUT, pin_signal: ADC0_B13/PTB3/WUU0_P14/LPSPI1_SOUT/LPUART1_RX/TPM1_CH3/FLEXIO0_D29, pull_select: up, pull_enable: enable,
    slew_rate: fast, open_drain: disable, drive_strength: high}
  - {pin_num: '46', peripheral: LPSPI1, signal: PCS0, pin_signal: ADC0_B10/PTB0/WUU0_P13/LPSPI1_PCS0/TPM1_CH0/FLEXIO0_D26, pull_select: up, pull_enable: enable, slew_rate: fast,
    open_drain: disable, drive_strength: high}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */
/* clang-format on */

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : LPSPI1_InitPins
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
void LPSPI1_InitPins(void)
{
    /* Clock Configuration: Peripheral clocks are enabled; module does not stall low power mode entry */
    CLOCK_EnableClock(kCLOCK_PortB);

    const port_pin_config_t LPSPI1_PCS0 = {/* Internal pull-up resistor is enabled */
                                           (uint16_t)kPORT_PullUp,
                                           /* Low internal pull resistor value is selected. */
                                           (uint16_t)kPORT_LowPullResistor,
                                           /* Fast slew rate is configured */
                                           (uint16_t)kPORT_FastSlewRate,
                                           /* Passive input filter is disabled */
                                           (uint16_t)kPORT_PassiveFilterDisable,
                                           /* Open drain output is disabled */
                                           (uint16_t)kPORT_OpenDrainDisable,
                                           /* High drive strength is configured */
                                           (uint16_t)kPORT_HighDriveStrength,
                                           /* Normal drive strength is configured */
                                           (uint16_t)kPORT_NormalDriveStrength,
                                           /* Pin is configured as LPSPI1_PCS0 */
                                           (uint16_t)kPORT_MuxAlt2,
                                           /* Pin Control Register fields [15:0] are not locked */
                                           (uint16_t)kPORT_UnlockRegister};
    /* PORTB0 (pin 46) is configured as LPSPI1_PCS0 */
    PORT_SetPinConfig(LPSPI1_INITPINS_LPSPI1_PCS0_PORT, LPSPI1_INITPINS_LPSPI1_PCS0_PIN, &LPSPI1_PCS0);

    const port_pin_config_t LPSPI1_IN = {/* Internal pull-up resistor is enabled */
                                         (uint16_t)kPORT_PullUp,
                                         /* Low internal pull resistor value is selected. */
                                         (uint16_t)kPORT_LowPullResistor,
                                         /* Fast slew rate is configured */
                                         (uint16_t)kPORT_FastSlewRate,
                                         /* Passive input filter is disabled */
                                         (uint16_t)kPORT_PassiveFilterDisable,
                                         /* Open drain output is disabled */
                                         (uint16_t)kPORT_OpenDrainDisable,
                                         /* High drive strength is configured */
                                         (uint16_t)kPORT_HighDriveStrength,
                                         /* Normal drive strength is configured */
                                         (uint16_t)kPORT_NormalDriveStrength,
                                         /* Pin is configured as LPSPI1_SIN */
                                         (uint16_t)kPORT_MuxAlt2,
                                         /* Pin Control Register fields [15:0] are not locked */
                                         (uint16_t)kPORT_UnlockRegister};
    /* PORTB1 (pin 47) is configured as LPSPI1_SIN */
    PORT_SetPinConfig(LPSPI1_INITPINS_LPSPI1_IN_PORT, LPSPI1_INITPINS_LPSPI1_IN_PIN, &LPSPI1_IN);

    const port_pin_config_t LPSPI1_SCK = {/* Internal pull-up resistor is enabled */
                                          (uint16_t)kPORT_PullUp,
                                          /* Low internal pull resistor value is selected. */
                                          (uint16_t)kPORT_LowPullResistor,
                                          /* Fast slew rate is configured */
                                          (uint16_t)kPORT_FastSlewRate,
                                          /* Passive input filter is disabled */
                                          (uint16_t)kPORT_PassiveFilterDisable,
                                          /* Open drain output is disabled */
                                          (uint16_t)kPORT_OpenDrainDisable,
                                          /* High drive strength is configured */
                                          (uint16_t)kPORT_HighDriveStrength,
                                          /* Normal drive strength is configured */
                                          (uint16_t)kPORT_NormalDriveStrength,
                                          /* Pin is configured as LPSPI1_SCK */
                                          (uint16_t)kPORT_MuxAlt2,
                                          /* Pin Control Register fields [15:0] are not locked */
                                          (uint16_t)kPORT_UnlockRegister};
    /* PORTB2 (pin 48) is configured as LPSPI1_SCK */
    PORT_SetPinConfig(LPSPI1_INITPINS_LPSPI1_SCK_PORT, LPSPI1_INITPINS_LPSPI1_SCK_PIN, &LPSPI1_SCK);

    const port_pin_config_t LPSPI1_OUT = {/* Internal pull-up resistor is enabled */
                                          (uint16_t)kPORT_PullUp,
                                          /* Low internal pull resistor value is selected. */
                                          (uint16_t)kPORT_LowPullResistor,
                                          /* Fast slew rate is configured */
                                          (uint16_t)kPORT_FastSlewRate,
                                          /* Passive input filter is disabled */
                                          (uint16_t)kPORT_PassiveFilterDisable,
                                          /* Open drain output is disabled */
                                          (uint16_t)kPORT_OpenDrainDisable,
                                          /* High drive strength is configured */
                                          (uint16_t)kPORT_HighDriveStrength,
                                          /* Normal drive strength is configured */
                                          (uint16_t)kPORT_NormalDriveStrength,
                                          /* Pin is configured as LPSPI1_SOUT */
                                          (uint16_t)kPORT_MuxAlt2,
                                          /* Pin Control Register fields [15:0] are not locked */
                                          (uint16_t)kPORT_UnlockRegister};
    /* PORTB3 (pin 1) is configured as LPSPI1_SOUT */
    PORT_SetPinConfig(LPSPI1_INITPINS_LPSPI1_OUT_PORT, LPSPI1_INITPINS_LPSPI1_OUT_PIN, &LPSPI1_OUT);
}

/* clang-format off */
/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
LPSPI0_DeinitPins:
- options: {callFromInitBoot: 'false', coreID: cm33, enableClock: 'true'}
- pin_list:
  - {pin_num: '11', peripheral: ADC0, signal: 'A, 12', pin_signal: ADC0_A12/PTA16/RF_NOT_ALLOWED/LPSPI0_PCS0/EWM0_OUT_b/LPI2C0_SCLS/TPM0_CH4/LPUART0_RX/RF_GPO_8/FLEXIO0_D5,
    pull_select: down, pull_enable: disable, slew_rate: fast, open_drain: disable, drive_strength: low}
  - {pin_num: '12', peripheral: ADC0, signal: 'A, 13', pin_signal: ADC0_A13/PTA17/WUU0_P3/RF_NOT_ALLOWED/LPSPI0_SIN/EWM0_IN/LPI2C0_SDAS/TPM0_CH5/LPUART0_TX/RF_GPO_7/RF_GPO_8/FLEXIO0_D6,
    pull_select: down, pull_enable: disable, slew_rate: fast, open_drain: disable, drive_strength: low}
  - {pin_num: '13', peripheral: LPCMP1, signal: 'IN, 1', pin_signal: CMP1_IN1/PTA18/LPSPI0_SOUT/LPUART0_CTS_b/LPI2C0_SDA/TPM0_CH3/RF_GPO_0/LPUART0_RX, pull_select: down,
    pull_enable: disable, pull_value: low, slew_rate: fast, passive_filter: disable, open_drain: disable, drive_strength: low, drive_strength_1: normal}
  - {pin_num: '14', peripheral: LPCMP1, signal: 'IN, 0', pin_signal: CMP1_IN0/PTA19/WUU0_P4/LPSPI0_SCK/LPUART0_RTS_b/LPI2C0_SCL/TPM0_CH2/RF_GPO_1, pull_select: down,
    pull_enable: disable, pull_value: low, slew_rate: fast, passive_filter: disable, open_drain: disable, drive_strength: low, drive_strength_1: normal}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */
/* clang-format on */

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : LPSPI0_DeinitPins
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
void LPSPI0_DeinitPins(void)
{
    /* Clock Configuration: Peripheral clocks are enabled; module does not stall low power mode entry */
    CLOCK_EnableClock(kCLOCK_PortA);

    const port_pin_config_t porta16_pin11_config = {/* Internal pull-up/down resistor is disabled */
                                                    (uint16_t)kPORT_PullDisable,
                                                    /* Low internal pull resistor value is selected. */
                                                    (uint16_t)kPORT_LowPullResistor,
                                                    /* Fast slew rate is configured */
                                                    (uint16_t)kPORT_FastSlewRate,
                                                    /* Passive input filter is disabled */
                                                    (uint16_t)kPORT_PassiveFilterDisable,
                                                    /* Open drain output is disabled */
                                                    (uint16_t)kPORT_OpenDrainDisable,
                                                    /* Low drive strength is configured */
                                                    (uint16_t)kPORT_LowDriveStrength,
                                                    /* Normal drive strength is configured */
                                                    (uint16_t)kPORT_NormalDriveStrength,
                                                    /* Pin is configured as ADC0_A12 */
                                                    (uint16_t)kPORT_PinDisabledOrAnalog,
                                                    /* Pin Control Register fields [15:0] are not locked */
                                                    (uint16_t)kPORT_UnlockRegister};
    /* PORTA16 (pin 11) is configured as ADC0_A12 */
    PORT_SetPinConfig(PORTA, 16U, &porta16_pin11_config);

    const port_pin_config_t porta17_pin12_config = {/* Internal pull-up/down resistor is disabled */
                                                    (uint16_t)kPORT_PullDisable,
                                                    /* Low internal pull resistor value is selected. */
                                                    (uint16_t)kPORT_LowPullResistor,
                                                    /* Fast slew rate is configured */
                                                    (uint16_t)kPORT_FastSlewRate,
                                                    /* Passive input filter is disabled */
                                                    (uint16_t)kPORT_PassiveFilterDisable,
                                                    /* Open drain output is disabled */
                                                    (uint16_t)kPORT_OpenDrainDisable,
                                                    /* Low drive strength is configured */
                                                    (uint16_t)kPORT_LowDriveStrength,
                                                    /* Normal drive strength is configured */
                                                    (uint16_t)kPORT_NormalDriveStrength,
                                                    /* Pin is configured as ADC0_A13 */
                                                    (uint16_t)kPORT_PinDisabledOrAnalog,
                                                    /* Pin Control Register fields [15:0] are not locked */
                                                    (uint16_t)kPORT_UnlockRegister};
    /* PORTA17 (pin 12) is configured as ADC0_A13 */
    PORT_SetPinConfig(PORTA, 17U, &porta17_pin12_config);

    const port_pin_config_t porta18_pin13_config = {/* Internal pull-up/down resistor is disabled */
                                                    (uint16_t)kPORT_PullDisable,
                                                    /* Low internal pull resistor value is selected. */
                                                    (uint16_t)kPORT_LowPullResistor,
                                                    /* Fast slew rate is configured */
                                                    (uint16_t)kPORT_FastSlewRate,
                                                    /* Passive input filter is disabled */
                                                    (uint16_t)kPORT_PassiveFilterDisable,
                                                    /* Open drain output is disabled */
                                                    (uint16_t)kPORT_OpenDrainDisable,
                                                    /* Low drive strength is configured */
                                                    (uint16_t)kPORT_LowDriveStrength,
                                                    /* Normal drive strength is configured */
                                                    (uint16_t)kPORT_NormalDriveStrength,
                                                    /* Pin is configured as CMP1_IN1 */
                                                    (uint16_t)kPORT_PinDisabledOrAnalog,
                                                    /* Pin Control Register fields [15:0] are not locked */
                                                    (uint16_t)kPORT_UnlockRegister};
    /* PORTA18 (pin 13) is configured as CMP1_IN1 */
    PORT_SetPinConfig(PORTA, 18U, &porta18_pin13_config);

    const port_pin_config_t porta19_pin14_config = {/* Internal pull-up/down resistor is disabled */
                                                    (uint16_t)kPORT_PullDisable,
                                                    /* Low internal pull resistor value is selected. */
                                                    (uint16_t)kPORT_LowPullResistor,
                                                    /* Fast slew rate is configured */
                                                    (uint16_t)kPORT_FastSlewRate,
                                                    /* Passive input filter is disabled */
                                                    (uint16_t)kPORT_PassiveFilterDisable,
                                                    /* Open drain output is disabled */
                                                    (uint16_t)kPORT_OpenDrainDisable,
                                                    /* Low drive strength is configured */
                                                    (uint16_t)kPORT_LowDriveStrength,
                                                    /* Normal drive strength is configured */
                                                    (uint16_t)kPORT_NormalDriveStrength,
                                                    /* Pin is configured as CMP1_IN0 */
                                                    (uint16_t)kPORT_PinDisabledOrAnalog,
                                                    /* Pin Control Register fields [15:0] are not locked */
                                                    (uint16_t)kPORT_UnlockRegister};
    /* PORTA19 (pin 14) is configured as CMP1_IN0 */
    PORT_SetPinConfig(PORTA, 19U, &porta19_pin14_config);
}

/* clang-format off */
/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
LPSPI1_DeinitPins:
- options: {callFromInitBoot: 'false', coreID: cm33, enableClock: 'true'}
- pin_list:
  - {pin_num: '48', peripheral: ADC0, signal: 'B, 12', pin_signal: ADC0_B12/PTB2/LPSPI1_SCK/LPUART1_TX/TPM1_CH2/FLEXIO0_D28, pull_select: down, pull_enable: disable,
    slew_rate: fast, open_drain: disable, drive_strength: low}
  - {pin_num: '47', peripheral: ADC0, signal: 'B, 11', pin_signal: ADC0_B11/PTB1/LPSPI1_SIN/TPM1_CH1/FLEXIO0_D27, pull_select: down, pull_enable: disable, slew_rate: fast,
    open_drain: disable, drive_strength: low}
  - {pin_num: '1', peripheral: ADC0, signal: 'B, 13', pin_signal: ADC0_B13/PTB3/WUU0_P14/LPSPI1_SOUT/LPUART1_RX/TPM1_CH3/FLEXIO0_D29, pull_select: down, pull_enable: disable,
    slew_rate: fast, open_drain: disable, drive_strength: low}
  - {pin_num: '46', peripheral: ADC0, signal: 'B, 10', pin_signal: ADC0_B10/PTB0/WUU0_P13/LPSPI1_PCS0/TPM1_CH0/FLEXIO0_D26, pull_select: down, pull_enable: disable,
    slew_rate: fast, open_drain: disable, drive_strength: low}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */
/* clang-format on */

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : LPSPI1_DeinitPins
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
void LPSPI1_DeinitPins(void)
{
    /* Clock Configuration: Peripheral clocks are enabled; module does not stall low power mode entry */
    CLOCK_EnableClock(kCLOCK_PortB);

    const port_pin_config_t LPSPI1_PCS0 = {/* Internal pull-up/down resistor is disabled */
                                           (uint16_t)kPORT_PullDisable,
                                           /* Low internal pull resistor value is selected. */
                                           (uint16_t)kPORT_LowPullResistor,
                                           /* Fast slew rate is configured */
                                           (uint16_t)kPORT_FastSlewRate,
                                           /* Passive input filter is disabled */
                                           (uint16_t)kPORT_PassiveFilterDisable,
                                           /* Open drain output is disabled */
                                           (uint16_t)kPORT_OpenDrainDisable,
                                           /* Low drive strength is configured */
                                           (uint16_t)kPORT_LowDriveStrength,
                                           /* Normal drive strength is configured */
                                           (uint16_t)kPORT_NormalDriveStrength,
                                           /* Pin is configured as ADC0_B10 */
                                           (uint16_t)kPORT_PinDisabledOrAnalog,
                                           /* Pin Control Register fields [15:0] are not locked */
                                           (uint16_t)kPORT_UnlockRegister};
    /* PORTB0 (pin 46) is configured as ADC0_B10 */
    PORT_SetPinConfig(LPSPI1_DEINITPINS_LPSPI1_PCS0_PORT, LPSPI1_DEINITPINS_LPSPI1_PCS0_PIN, &LPSPI1_PCS0);

    const port_pin_config_t LPSPI1_IN = {/* Internal pull-up/down resistor is disabled */
                                         (uint16_t)kPORT_PullDisable,
                                         /* Low internal pull resistor value is selected. */
                                         (uint16_t)kPORT_LowPullResistor,
                                         /* Fast slew rate is configured */
                                         (uint16_t)kPORT_FastSlewRate,
                                         /* Passive input filter is disabled */
                                         (uint16_t)kPORT_PassiveFilterDisable,
                                         /* Open drain output is disabled */
                                         (uint16_t)kPORT_OpenDrainDisable,
                                         /* Low drive strength is configured */
                                         (uint16_t)kPORT_LowDriveStrength,
                                         /* Normal drive strength is configured */
                                         (uint16_t)kPORT_NormalDriveStrength,
                                         /* Pin is configured as ADC0_B11 */
                                         (uint16_t)kPORT_PinDisabledOrAnalog,
                                         /* Pin Control Register fields [15:0] are not locked */
                                         (uint16_t)kPORT_UnlockRegister};
    /* PORTB1 (pin 47) is configured as ADC0_B11 */
    PORT_SetPinConfig(LPSPI1_DEINITPINS_LPSPI1_IN_PORT, LPSPI1_DEINITPINS_LPSPI1_IN_PIN, &LPSPI1_IN);

    const port_pin_config_t LPSPI1_SCK = {/* Internal pull-up/down resistor is disabled */
                                          (uint16_t)kPORT_PullDisable,
                                          /* Low internal pull resistor value is selected. */
                                          (uint16_t)kPORT_LowPullResistor,
                                          /* Fast slew rate is configured */
                                          (uint16_t)kPORT_FastSlewRate,
                                          /* Passive input filter is disabled */
                                          (uint16_t)kPORT_PassiveFilterDisable,
                                          /* Open drain output is disabled */
                                          (uint16_t)kPORT_OpenDrainDisable,
                                          /* Low drive strength is configured */
                                          (uint16_t)kPORT_LowDriveStrength,
                                          /* Normal drive strength is configured */
                                          (uint16_t)kPORT_NormalDriveStrength,
                                          /* Pin is configured as ADC0_B12 */
                                          (uint16_t)kPORT_PinDisabledOrAnalog,
                                          /* Pin Control Register fields [15:0] are not locked */
                                          (uint16_t)kPORT_UnlockRegister};
    /* PORTB2 (pin 48) is configured as ADC0_B12 */
    PORT_SetPinConfig(LPSPI1_DEINITPINS_LPSPI1_SCK_PORT, LPSPI1_DEINITPINS_LPSPI1_SCK_PIN, &LPSPI1_SCK);

    const port_pin_config_t LPSPI1_OUT = {/* Internal pull-up/down resistor is disabled */
                                          (uint16_t)kPORT_PullDisable,
                                          /* Low internal pull resistor value is selected. */
                                          (uint16_t)kPORT_LowPullResistor,
                                          /* Fast slew rate is configured */
                                          (uint16_t)kPORT_FastSlewRate,
                                          /* Passive input filter is disabled */
                                          (uint16_t)kPORT_PassiveFilterDisable,
                                          /* Open drain output is disabled */
                                          (uint16_t)kPORT_OpenDrainDisable,
                                          /* Low drive strength is configured */
                                          (uint16_t)kPORT_LowDriveStrength,
                                          /* Normal drive strength is configured */
                                          (uint16_t)kPORT_NormalDriveStrength,
                                          /* Pin is configured as ADC0_B13 */
                                          (uint16_t)kPORT_PinDisabledOrAnalog,
                                          /* Pin Control Register fields [15:0] are not locked */
                                          (uint16_t)kPORT_UnlockRegister};
    /* PORTB3 (pin 1) is configured as ADC0_B13 */
    PORT_SetPinConfig(LPSPI1_DEINITPINS_LPSPI1_OUT_PORT, LPSPI1_DEINITPINS_LPSPI1_OUT_PIN, &LPSPI1_OUT);
}

/* clang-format off */
/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
LPUART1_InitPins:
- options: {callFromInitBoot: 'false', coreID: cm33, enableClock: 'true'}
- pin_list:
  - {pin_num: '39', peripheral: LPUART1, signal: RX, pin_signal: PTC2/WUU0_P9/LPSPI1_SOUT/LPUART1_RX/LPI2C1_SCLS/TPM1_CH2/I3C0_PUR/FLEXIO0_D18, pull_select: down,
    pull_enable: disable, slew_rate: fast, open_drain: disable, drive_strength: low}
  - {pin_num: '40', peripheral: LPUART1, signal: TX, pin_signal: PTC3/LPSPI1_SCK/LPUART1_TX/LPI2C1_SDAS/TPM1_CH3/FLEXIO0_D19, pull_select: down, pull_enable: disable,
    slew_rate: fast, open_drain: disable, drive_strength: low}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */
/* clang-format on */

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : LPUART1_InitPins
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
void LPUART1_InitPins(void)
{
    /* Clock Configuration: Peripheral clocks are enabled; module does not stall low power mode entry */
    CLOCK_EnableClock(kCLOCK_PortC);

    const port_pin_config_t portc2_pin39_config = {/* Internal pull-up/down resistor is disabled */
                                                   (uint16_t)kPORT_PullDisable,
                                                   /* Low internal pull resistor value is selected. */
                                                   (uint16_t)kPORT_LowPullResistor,
                                                   /* Fast slew rate is configured */
                                                   (uint16_t)kPORT_FastSlewRate,
                                                   /* Passive input filter is disabled */
                                                   (uint16_t)kPORT_PassiveFilterDisable,
                                                   /* Open drain output is disabled */
                                                   (uint16_t)kPORT_OpenDrainDisable,
                                                   /* Low drive strength is configured */
                                                   (uint16_t)kPORT_LowDriveStrength,
                                                   /* Normal drive strength is configured */
                                                   (uint16_t)kPORT_NormalDriveStrength,
                                                   /* Pin is configured as LPUART1_RX */
                                                   (uint16_t)kPORT_MuxAlt3,
                                                   /* Pin Control Register fields [15:0] are not locked */
                                                   (uint16_t)kPORT_UnlockRegister};
    /* PORTC2 (pin 39) is configured as LPUART1_RX */
    PORT_SetPinConfig(PORTC, 2U, &portc2_pin39_config);

    const port_pin_config_t portc3_pin40_config = {/* Internal pull-up/down resistor is disabled */
                                                   (uint16_t)kPORT_PullDisable,
                                                   /* Low internal pull resistor value is selected. */
                                                   (uint16_t)kPORT_LowPullResistor,
                                                   /* Fast slew rate is configured */
                                                   (uint16_t)kPORT_FastSlewRate,
                                                   /* Passive input filter is disabled */
                                                   (uint16_t)kPORT_PassiveFilterDisable,
                                                   /* Open drain output is disabled */
                                                   (uint16_t)kPORT_OpenDrainDisable,
                                                   /* Low drive strength is configured */
                                                   (uint16_t)kPORT_LowDriveStrength,
                                                   /* Normal drive strength is configured */
                                                   (uint16_t)kPORT_NormalDriveStrength,
                                                   /* Pin is configured as LPUART1_TX */
                                                   (uint16_t)kPORT_MuxAlt3,
                                                   /* Pin Control Register fields [15:0] are not locked */
                                                   (uint16_t)kPORT_UnlockRegister};
    /* PORTC3 (pin 40) is configured as LPUART1_TX */
    PORT_SetPinConfig(PORTC, 3U, &portc3_pin40_config);
}

/* clang-format off */
/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
LPUART1_DeinitPins:
- options: {callFromInitBoot: 'false', coreID: cm33, enableClock: 'true'}
- pin_list:
  - {pin_num: '39', peripheral: n/a, signal: disabled, pin_signal: PTC2/WUU0_P9/LPSPI1_SOUT/LPUART1_RX/LPI2C1_SCLS/TPM1_CH2/I3C0_PUR/FLEXIO0_D18, pull_select: down,
    pull_enable: disable, slew_rate: fast, open_drain: disable, drive_strength: low}
  - {pin_num: '40', peripheral: n/a, signal: disabled, pin_signal: PTC3/LPSPI1_SCK/LPUART1_TX/LPI2C1_SDAS/TPM1_CH3/FLEXIO0_D19, pull_select: down, pull_enable: disable,
    slew_rate: fast, open_drain: disable, drive_strength: low}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */
/* clang-format on */

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : LPUART1_DeinitPins
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
void LPUART1_DeinitPins(void)
{
    /* Clock Configuration: Peripheral clocks are enabled; module does not stall low power mode entry */
    CLOCK_EnableClock(kCLOCK_PortC);

    const port_pin_config_t portc2_pin39_config = {/* Internal pull-up/down resistor is disabled */
                                                   (uint16_t)kPORT_PullDisable,
                                                   /* Low internal pull resistor value is selected. */
                                                   (uint16_t)kPORT_LowPullResistor,
                                                   /* Fast slew rate is configured */
                                                   (uint16_t)kPORT_FastSlewRate,
                                                   /* Passive input filter is disabled */
                                                   (uint16_t)kPORT_PassiveFilterDisable,
                                                   /* Open drain output is disabled */
                                                   (uint16_t)kPORT_OpenDrainDisable,
                                                   /* Low drive strength is configured */
                                                   (uint16_t)kPORT_LowDriveStrength,
                                                   /* Normal drive strength is configured */
                                                   (uint16_t)kPORT_NormalDriveStrength,
                                                   /* Pin is disabled */
                                                   (uint16_t)kPORT_PinDisabledOrAnalog,
                                                   /* Pin Control Register fields [15:0] are not locked */
                                                   (uint16_t)kPORT_UnlockRegister};
    /* PORTC2 (pin 39) is disabled */
    PORT_SetPinConfig(PORTC, 2U, &portc2_pin39_config);

    const port_pin_config_t portc3_pin40_config = {/* Internal pull-up/down resistor is disabled */
                                                   (uint16_t)kPORT_PullDisable,
                                                   /* Low internal pull resistor value is selected. */
                                                   (uint16_t)kPORT_LowPullResistor,
                                                   /* Fast slew rate is configured */
                                                   (uint16_t)kPORT_FastSlewRate,
                                                   /* Passive input filter is disabled */
                                                   (uint16_t)kPORT_PassiveFilterDisable,
                                                   /* Open drain output is disabled */
                                                   (uint16_t)kPORT_OpenDrainDisable,
                                                   /* Low drive strength is configured */
                                                   (uint16_t)kPORT_LowDriveStrength,
                                                   /* Normal drive strength is configured */
                                                   (uint16_t)kPORT_NormalDriveStrength,
                                                   /* Pin is disabled */
                                                   (uint16_t)kPORT_PinDisabledOrAnalog,
                                                   /* Pin Control Register fields [15:0] are not locked */
                                                   (uint16_t)kPORT_UnlockRegister};
    /* PORTC3 (pin 40) is disabled */
    PORT_SetPinConfig(PORTC, 3U, &portc3_pin40_config);
}
/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
