/*
 * Copyright 2024 NXP
 *
 * SPDX-License-Identifier: BSD-3-Clause
 */

/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

#ifndef _PIN_MUX_H_
#define _PIN_MUX_H_

/*!
 * @addtogroup pin_mux
 * @{
 */

/***********************************************************************************************************************
 * API
 **********************************************************************************************************************/

#if defined(__cplusplus)
extern "C" {
#endif

/*!
 * @brief Calls initialization functions.
 *
 */
void BOARD_InitBootPins(void);

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitPins(void);

#define BOARD_INITPINS_LED_GREEN_GPIO GPIOA                /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_LED_GREEN_GPIO_PIN_MASK (1U << 19U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_LED_GREEN_PORT PORTA                /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_LED_GREEN_PIN 19U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_LED_GREEN_PIN_MASK (1U << 19U)      /*!<@brief PORT pin mask */
                                                           /* @} */

#define BOARD_INITPINS_LED_BLUE_GPIO GPIOA                /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_LED_BLUE_GPIO_PIN_MASK (1U << 20U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_LED_BLUE_PORT PORTA                /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_LED_BLUE_PIN 20U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_LED_BLUE_PIN_MASK (1U << 20U)      /*!<@brief PORT pin mask */
                                                           /* @} */

#define BOARD_INITPINS_LED_RED_GPIO GPIOA                /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_LED_RED_GPIO_PIN_MASK (1U << 21U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_LED_RED_PORT PORTA                /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_LED_RED_PIN 21U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_LED_RED_PIN_MASK (1U << 21U)      /*!<@brief PORT pin mask */

/*! @name PORTB5 (number 3), LPI2C1_SCL
  @{ */

/* Symbols to be used with PORT driver */
#define LPI2C1_INITPINS_LPI2C1_SCL_PORT PORTB               /*!<@brief PORT peripheral base pointer */
#define LPI2C1_INITPINS_LPI2C1_SCL_PIN 5U                   /*!<@brief PORT pin number */
#define LPI2C1_INITPINS_LPI2C1_SCL_PIN_MASK (1U << 5U)      /*!<@brief PORT pin mask */
                                                            /* @} */

/*! @name PORTB4 (number 2), LPI2C1_SDA
  @{ */

/* Symbols to be used with PORT driver */
#define LPI2C1_INITPINS_LPI2C1_SDA_PORT PORTB               /*!<@brief PORT peripheral base pointer */
#define LPI2C1_INITPINS_LPI2C1_SDA_PIN 4U                   /*!<@brief PORT pin number */
#define LPI2C1_INITPINS_LPI2C1_SDA_PIN_MASK (1U << 4U)      /*!<@brief PORT pin mask */
                                                            /* @} */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void LPI2C1_InitPins(void);

/*! @name PORTB5 (number 3), LPI2C1_SCL
  @{ */

/* Symbols to be used with PORT driver */
#define LPI2C1_DEINITPINS_LPI2C1_SCL_PORT PORTB               /*!<@brief PORT peripheral base pointer */
#define LPI2C1_DEINITPINS_LPI2C1_SCL_PIN 5U                   /*!<@brief PORT pin number */
#define LPI2C1_DEINITPINS_LPI2C1_SCL_PIN_MASK (1U << 5U)      /*!<@brief PORT pin mask */
                                                              /* @} */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void LPI2C1_DeinitPins(void);

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void LPSPI0_InitPins(void);

/*! @name PORTB2 (number 48), LPSPI1_SCK
  @{ */

/* Symbols to be used with PORT driver */
#define LPSPI1_INITPINS_LPSPI1_SCK_PORT PORTB               /*!<@brief PORT peripheral base pointer */
#define LPSPI1_INITPINS_LPSPI1_SCK_PIN 2U                   /*!<@brief PORT pin number */
#define LPSPI1_INITPINS_LPSPI1_SCK_PIN_MASK (1U << 2U)      /*!<@brief PORT pin mask */
                                                            /* @} */

/*! @name PORTB1 (number 47), LPSPI1_IN
  @{ */

/* Symbols to be used with PORT driver */
#define LPSPI1_INITPINS_LPSPI1_IN_PORT PORTB               /*!<@brief PORT peripheral base pointer */
#define LPSPI1_INITPINS_LPSPI1_IN_PIN 1U                   /*!<@brief PORT pin number */
#define LPSPI1_INITPINS_LPSPI1_IN_PIN_MASK (1U << 1U)      /*!<@brief PORT pin mask */
                                                           /* @} */

/*! @name PORTB3 (number 1), LPSPI1_OUT
  @{ */

/* Symbols to be used with PORT driver */
#define LPSPI1_INITPINS_LPSPI1_OUT_PORT PORTB               /*!<@brief PORT peripheral base pointer */
#define LPSPI1_INITPINS_LPSPI1_OUT_PIN 3U                   /*!<@brief PORT pin number */
#define LPSPI1_INITPINS_LPSPI1_OUT_PIN_MASK (1U << 3U)      /*!<@brief PORT pin mask */
                                                            /* @} */

/*! @name PORTB0 (number 46), LPSPI1_PCS0
  @{ */

/* Symbols to be used with PORT driver */
#define LPSPI1_INITPINS_LPSPI1_PCS0_PORT PORTB               /*!<@brief PORT peripheral base pointer */
#define LPSPI1_INITPINS_LPSPI1_PCS0_PIN 0U                   /*!<@brief PORT pin number */
#define LPSPI1_INITPINS_LPSPI1_PCS0_PIN_MASK (1U << 0U)      /*!<@brief PORT pin mask */
                                                             /* @} */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void LPSPI1_InitPins(void);

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void LPSPI0_DeinitPins(void);

/*! @name PORTB2 (number 48), LPSPI1_SCK
  @{ */

/* Symbols to be used with PORT driver */
#define LPSPI1_DEINITPINS_LPSPI1_SCK_PORT PORTB               /*!<@brief PORT peripheral base pointer */
#define LPSPI1_DEINITPINS_LPSPI1_SCK_PIN 2U                   /*!<@brief PORT pin number */
#define LPSPI1_DEINITPINS_LPSPI1_SCK_PIN_MASK (1U << 2U)      /*!<@brief PORT pin mask */
                                                              /* @} */

/*! @name PORTB1 (number 47), LPSPI1_IN
  @{ */

/* Symbols to be used with PORT driver */
#define LPSPI1_DEINITPINS_LPSPI1_IN_PORT PORTB               /*!<@brief PORT peripheral base pointer */
#define LPSPI1_DEINITPINS_LPSPI1_IN_PIN 1U                   /*!<@brief PORT pin number */
#define LPSPI1_DEINITPINS_LPSPI1_IN_PIN_MASK (1U << 1U)      /*!<@brief PORT pin mask */
                                                             /* @} */

/*! @name PORTB3 (number 1), LPSPI1_OUT
  @{ */

/* Symbols to be used with PORT driver */
#define LPSPI1_DEINITPINS_LPSPI1_OUT_PORT PORTB               /*!<@brief PORT peripheral base pointer */
#define LPSPI1_DEINITPINS_LPSPI1_OUT_PIN 3U                   /*!<@brief PORT pin number */
#define LPSPI1_DEINITPINS_LPSPI1_OUT_PIN_MASK (1U << 3U)      /*!<@brief PORT pin mask */
                                                              /* @} */

/*! @name PORTB0 (number 46), LPSPI1_PCS0
  @{ */

/* Symbols to be used with PORT driver */
#define LPSPI1_DEINITPINS_LPSPI1_PCS0_PORT PORTB               /*!<@brief PORT peripheral base pointer */
#define LPSPI1_DEINITPINS_LPSPI1_PCS0_PIN 0U                   /*!<@brief PORT pin number */
#define LPSPI1_DEINITPINS_LPSPI1_PCS0_PIN_MASK (1U << 0U)      /*!<@brief PORT pin mask */
                                                               /* @} */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void LPSPI1_DeinitPins(void);

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void LPUART1_InitPins(void);

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void LPUART1_DeinitPins(void);

#if defined(__cplusplus)
}
#endif

/*!
 * @}
 */
#endif /* _PIN_MUX_H_ */

/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
